export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const FORM_LOADING = 'FORM_LOADING'
export const ADD_FORM = 'ADD_FORM'
export const UPDATE_FORM = 'UPDATE_FORM'
export const UPDATE_FORMS = 'UPDATE_FORMS'
export const GET_FORMS = 'GET_FORMS'
export const GET_FORM = 'GET_FORM'
export const DELETE_FORM = 'DELETE_FORM'
export const CLEAR_FORMS = 'CLEAR_FORMS'

export const SUBSCRIPTION_LOADING = 'SUBSCRIPTION_LOADING'
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS'
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION'

export const USER_LOADING = 'USER_LOADING'
export const GET_USER = 'GET_USER'
